#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pysendfile
Version  : 2.0.1
Release  : 23
URL      : http://pypi.debian.net/pysendfile/pysendfile-2.0.1.tar.gz
Source0  : http://pypi.debian.net/pysendfile/pysendfile-2.0.1.tar.gz
Summary  : A Python interface to sendfile(2)
Group    : Development/Tools
License  : MIT
Requires: pysendfile-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
.. image:: https://pypip.in/d/pysendfile/badge.png
:target: https://crate.io/packages/pysendfile/
:alt: Download this month

%package python
Summary: python components for the pysendfile package.
Group: Default

%description python
python components for the pysendfile package.


%prep
%setup -q -n pysendfile-2.0.1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
