#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pysendfile
Version  : 2.0.1
Release  : 31
URL      : http://pypi.debian.net/pysendfile/pysendfile-2.0.1.tar.gz
Source0  : http://pypi.debian.net/pysendfile/pysendfile-2.0.1.tar.gz
Summary  : A Python interface to sendfile(2)
Group    : Development/Tools
License  : MIT
Requires: pysendfile-python3
Requires: pysendfile-license
Requires: pysendfile-python
BuildRequires : buildreq-distutils3
BuildRequires : py
BuildRequires : pytest

%description
.. image:: https://pypip.in/d/pysendfile/badge.png
:target: https://crate.io/packages/pysendfile/
:alt: Download this month

%package license
Summary: license components for the pysendfile package.
Group: Default

%description license
license components for the pysendfile package.


%package python
Summary: python components for the pysendfile package.
Group: Default
Requires: pysendfile-python3

%description python
python components for the pysendfile package.


%package python3
Summary: python3 components for the pysendfile package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pysendfile package.


%prep
%setup -q -n pysendfile-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533875980
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pysendfile
cp LICENSE %{buildroot}/usr/share/doc/pysendfile/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pysendfile/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
